model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: nvidia_nim/z-ai/glm-5.2
      api_key: os.environ/NVIDIA_NIM_API_KEY
      max_tokens: 4096
      # 🔥 FORCING TO FALSE: Overrides whatever Janitor AI sends in the background
      logprobs: false

  - model_name: gpt-4
    litellm_params:
      model: nvidia_nim/stepfun-ai/step-3.7-flash
      api_key: os.environ/NVIDIA_NIM_API_KEY
      max_tokens: 16384

litellm_settings:
  drop_params: true
